research_publicly_traded_company:
  description: >
    Conduct research into publicly traded company {company_name} and deliver a report with
    recommendations on whether to buy or sell the stock.
  expected_output: >
    A report that includes an in-depth analysis of the company's financials, market trends,
    and competitors as well as a clear recommendation on whether to buy or sell the stock.
  agent: equity_research_analyst

financial_analysis:
  description: >
    Conduct a thorough analysis of {company_stock}'s stock financial health and market performance. This includes examining key financial metrics such as
    P/E ratio, EPS growth, revenue trends, and debt-to-equity ratio. Also, analyze the stock's performance in comparison 
    to its industry peers and overall market trends.

  expected_output: >
    The final report must expand on the summary provided but now 
    including a clear assessment of the stock's financial standing, its strengths and weaknesses, 
    and how it fares against its competitors in the current market scenario.
    Make sure to use the most recent data possible.

research:
  description: >
    Collect and summarize recent news articles, press
    releases, and market analyses related to the {company_stock} stock and its industry.
    Pay special attention to any significant events, market sentiments, and analysts' opinions. 
    Also include upcoming events like earnings and others.

  expected_output: >
    A report that includes a comprehensive summary of the latest news, 
    any notable shifts in market sentiment, and potential impacts on the stock. Also make sure to return the stock ticker as {company_stock}.
    Make sure to use the most recent data as possible.

filings_analysis:
  description: >
    Analyze the latest 10-Q and 10-K filings from EDGAR for the stock {company_stock} in question. 
    Focus on key sections like Management's Discussion and analysis, financial statements, insider trading activity, 
    and any disclosed risks. Extract relevant data and insights that could influence
    the stock's future performance.

